//! The `lys/anchor-delegation/v1` fixed vector, pinned as literal hex.
//!
//! # Provenance — where these bytes came from, and why that is the whole point
//!
//! **A golden vector whose provenance is not written down decays into "a number
//! someone once printed."** Its entire authority is that it did not come from
//! the code it checks, and that claim is only worth something for as long as
//! somebody can still tell you how it was produced. So:
//!
//! 1. The values were derived **from the specification and the RFCs**
//!    (RFC 8032, RFC 8949 §4.2, RFC 9052 §4.4) by a third party, using
//!    `openssl` for the Ed25519 key derivation and signature and hand-assembled
//!    CBOR for the encoding. **Not** `ed25519-dalek`, so the signature is not
//!    this crate's signer agreeing with itself, and not this crate's `cbor`
//!    module, so the encoding is not this crate's encoder agreeing with itself.
//! 2. Independently, this crate's encoder produced its own bytes for the same
//!    inputs, without either side seeing the other's output first.
//! 3. The two were compared **programmatically, byte for byte**, on all five
//!    values below — protected header, payload, `Sig_structure`, signature, and
//!    the complete tagged artifact. They matched exactly.
//!
//! Two encoders, two signing implementations, one shared input: the
//! specification. That agreement is what is frozen here.
//!
//! The vector was regenerated from scratch when the adversarial review added
//! payload label 5 (`sequence`), by both parties separately, exactly as the
//! first one was. A vector regenerated by one side and copied by the other is
//! one party agreeing with itself, which is the defect this file exists to
//! prevent rather than to demonstrate.
//!
//! # Which axis of independence this is, and which it is not
//!
//! **Encoding, and key derivation.** Derived from the documents, by a different
//! tool, without reading the Rust.
//!
//! **Not platform, not custody, not review.** One machine, one toolchain. And a
//! frozen vector proves the code still emits what it emitted when the vector was
//! taken; it does **not** prove those bytes were the right ones to freeze. That
//! judgement is the specification's and the adversarial review's, and no test
//! can supply it.
//!
//! # Why every byte below is typed out rather than imported
//!
//! A test that imported `CONTENT_TYPE`, or built its expectation by calling the
//! encoder it is checking, moves wherever the code moves. It would be blind to
//! exactly the drift it exists to catch, which is not a hypothetical in this
//! repository: reversing the two public keys in the seal `info` left the entire
//! suite green, and so did changing that construction's domain tag. The fix was
//! `tests/seal_derivation.rs`, whose tag is the byte literal
//! `b"lys-sealed-envelope/v1"` and not the crate's constant. This file is the
//! same register applied to a wire format.
//!
//! Everything here is a constant this file can be **wrong** about, which is the
//! property that makes it worth having.
//!
//! # What one comparison pins
//!
//! `HEX_PREIMAGE` alone pins, in a single assertion: the `Sig_structure` array
//! shape and its `"Signature1"` context, the protected map's key order
//! `{1, 3, 4}`, the `alg = -8` encoding, the exact 45-byte content type string,
//! the `kid` being a **bstr** and not a tstr, `external_aad = h''`, the payload
//! map's key order `{1, 2, 3, 4, 5}`, the `role` encoding, and the head widths
//! of `not_before_unix_ms` (eight-byte) and `sequence` (two-byte). Any of those
//! changing in `src/delegation/` changes these bytes.
//!
//! `HEX_ARTIFACT` adds the tag `18` (`0xD2`), the four-element array, and the
//! **empty** unprotected bucket `0xA0`.
//!
//! `HEX_SIGNATURE` adds the one thing the two above cannot: that the private key
//! derivation and the Ed25519 signature itself match a different implementation.
//! Ed25519 is deterministic (RFC 8032), so for one seed and one message there is
//! exactly one correct signature — an agreement here is not a coincidence that a
//! looser verifier could also produce.
//!
//! # The positive control
//!
//! A file made only of equality assertions against literals cannot tell a
//! correct implementation from one that is broken in the same direction as the
//! literals. So the artifact is also **verified**, through `verify_delegation`,
//! against the root key and origin named here — and the reconstructed claim is
//! compared field by field. If the literals and the implementation were wrong
//! together in a way that broke the signature, that check would fail.
//!
//! # Availability
//!
//! Gated with the format it pins: with `unstable-anchor` off there is no
//! `delegation` module and this file compiles to nothing.

#![cfg(feature = "unstable-anchor")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use lys_core::Ed25519Identity;
use lys_core::delegation::{
    AnchorDelegation, DelegationClaim, DelegationRole, assemble_delegation, delegation_preimage,
    sign_delegation, verify_delegation,
};

// ---------------------------------------------------------------------------
// The vector's inputs, from the specification's §6.1 table.
// ---------------------------------------------------------------------------

/// Root Ed25519 seed: bytes `0x00..=0x1f`.
const ROOT_SEED: [u8; 32] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
];

/// Delegated Ed25519 seed: bytes `0x20..=0x3f`.
const DELEGATED_SEED: [u8; 32] = [
    0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f,
];

/// The vector's origin. `example.test` is a reserved name and deliberately not
/// a production origin: a committed constant naming a real one would be the
/// mistake the format's origin field exists to prevent.
const ORIGIN: &str = "example.test";

/// The vector's `not_before_unix_ms`. Written as a number, not imported.
const NOT_BEFORE_UNIX_MS: u64 = 1_700_000_000_000;

/// The vector's role, as the **wire integer**. Compared against
/// `DelegationRole::Operational.wire_value()` so the enum cannot silently
/// re-number itself.
const ROLE_WIRE_VALUE: u64 = 1;

/// The vector's `sequence` (spec §6.1). Chosen to expose bugs rather than to
/// look natural: not `0`, which is indistinguishable from a field an
/// implementation forgot to write and defaulted; not `1`, which `role` already
/// carries, so a field swap would be masked; and large enough to need a
/// **two-byte** head, a third width alongside `not_before`'s eight-byte and
/// `role`'s inline one — so a head-width bug has nowhere to hide.
///
/// `300` is `0x012c`, so the canonical encoding is `19012c`. A draft of the
/// specification once wrote that encoding as `190130`, which is 304: a
/// hand-written literal that was never recomputed. That is precisely the failure
/// mode this file exists to catch, appearing in the document rather than in the
/// code — and it is why `sequence` is asserted here as a *number* whose encoding
/// the frozen hex must contain, never as a hex literal copied from prose.
const SEQUENCE: u64 = 300;

// ---------------------------------------------------------------------------
// The vector's outputs. Literal hex; nothing here is computed from lys-core.
// ---------------------------------------------------------------------------

/// Root public key, which is also the protected `kid`.
const HEX_ROOT_PUBLIC_KEY: &str =
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8";

/// The public key being delegated to.
const HEX_DELEGATED_PUBLIC_KEY: &str =
    "29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7";

/// The protected header map, 86 bytes, **without** its bstr wrapper.
const HEX_PROTECTED: &str = "a3012703782d6170706c69636174696f6e2f766e642e6c79732e616e63686f722d\
64656c65676174696f6e2e76312b63626f7204582003a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc866\
4125531b8";

/// The embedded payload map, 66 bytes, **without** its bstr wrapper. Five
/// entries: the head is `0xa5`.
const HEX_PAYLOAD: &str = "a5016c6578616d706c652e7465737402582029acbae141bccaf0b22e1a94d34d0bc736\
1e526d0bfe12c89794bc9322966dd70301041b0000018bcfe568000519012c";

/// The RFC 9052 §4.4 `Sig_structure`, 169 bytes — the bytes the signature
/// covers.
const HEX_PREIMAGE: &str = "846a5369676e6174757265315856a3012703782d6170706c69636174696f6e2f766e6\
42e6c79732e616e63686f722d64656c65676174696f6e2e76312b63626f7204582003a107bff3ce10be1d70dd18e74bc0\
9967e4d6309ba50d5f1ddc8664125531b8405842a5016c6578616d706c652e7465737402582029acbae141bccaf0b22e1\
a94d34d0bc7361e526d0bfe12c89794bc9322966dd70301041b0000018bcfe568000519012c";

/// The Ed25519 signature, 64 bytes. Deterministic per RFC 8032, so this is the
/// only correct value for this key and this message.
const HEX_SIGNATURE: &str = "63211dff68f4e2bfea06ece8bf4caae231042eed7a768426555f9db361b724b0282e\
2a6d99370e0a801cfa168a68006445d91a1f639bf87c106156e16a54d603";

/// The complete tagged `COSE_Sign1`, 225 bytes.
const HEX_ARTIFACT: &str = "d2845856a3012703782d6170706c69636174696f6e2f766e642e6c79732e616e63686\
f722d64656c65676174696f6e2e76312b63626f7204582003a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1d\
dc8664125531b8a05842a5016c6578616d706c652e7465737402582029acbae141bccaf0b22e1a94d34d0bc7361e526d0\
bfe12c89794bc9322966dd70301041b0000018bcfe568000519012c584063211dff68f4e2bfea06ece8bf4caae231042e\
ed7a768426555f9db361b724b0282e2a6d99370e0a801cfa168a68006445d91a1f639bf87c106156e16a54d603";

// ---------------------------------------------------------------------------

fn to_hex(bytes: &[u8]) -> String {
    use std::fmt::Write;
    bytes.iter().fold(String::new(), |mut acc, byte| {
        let _ = write!(acc, "{byte:02x}");
        acc
    })
}

fn from_hex(hex: &str) -> Vec<u8> {
    assert!(hex.len() % 2 == 0, "odd-length hex literal");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex digit"))
        .collect()
}

/// The identity for a fixed seed, via the public `load` route. The `TempDir` is
/// returned because it must outlive the read.
fn identity(seed: &[u8; 32]) -> (tempfile::TempDir, Ed25519Identity) {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("key");
    std::fs::write(&path, seed).unwrap();
    let key = Ed25519Identity::load(&path).unwrap();
    (dir, key)
}

fn vector_claim(delegated_public_key: [u8; 32]) -> DelegationClaim {
    DelegationClaim {
        origin: ORIGIN.to_string(),
        delegated_public_key,
        role: DelegationRole::Operational,
        not_before_unix_ms: NOT_BEFORE_UNIX_MS,
        sequence: SEQUENCE,
    }
}

/// The literals are internally consistent, checked before they are used to
/// judge anything.
///
/// This is not ceremony. A mistyped literal — one nibble lost from a paste —
/// would otherwise show up as "the implementation drifted", and someone would
/// go looking in `src/` for a bug that is in this file. The lengths and the
/// containment relations are properties of the *specification*, so they can be
/// checked without consulting the implementation at all.
#[test]
fn the_frozen_literals_are_self_consistent() {
    assert_eq!(from_hex(HEX_ROOT_PUBLIC_KEY).len(), 32);
    assert_eq!(from_hex(HEX_DELEGATED_PUBLIC_KEY).len(), 32);
    assert_eq!(from_hex(HEX_PROTECTED).len(), 86, "spec §1.1");
    assert_eq!(from_hex(HEX_PAYLOAD).len(), 66, "spec §1.2, five entries");
    assert_eq!(from_hex(HEX_PREIMAGE).len(), 169, "spec §6.1");
    assert_eq!(from_hex(HEX_SIGNATURE).len(), 64);
    assert_eq!(from_hex(HEX_ARTIFACT).len(), 225, "spec §6.1");

    let preimage = from_hex(HEX_PREIMAGE);
    let protected = from_hex(HEX_PROTECTED);
    let payload = from_hex(HEX_PAYLOAD);

    // 12 = 0x84 (four-element array) + 0x6A + "Signature1".
    assert_eq!(
        &preimage[..12],
        b"\x84\x6aSignature1",
        "RFC 9052 §4.4 context"
    );
    // 0x58 0x56 is an 86-byte bstr head; 0x58 0x42 a 66-byte one.
    assert_eq!(&preimage[12..14], &[0x58, 0x56], "protected bstr head");
    assert_eq!(&preimage[14..14 + 86], &protected[..]);
    assert_eq!(preimage[100], 0x40, "external_aad must be h'' — spec §1.0");
    assert_eq!(&preimage[101..103], &[0x58, 0x42], "payload bstr head");
    assert_eq!(&preimage[103..], &payload[..]);

    let artifact = from_hex(HEX_ARTIFACT);
    assert_eq!(artifact[0], 0xd2, "tag 18 is mandatory — spec §1.0");
    assert_eq!(artifact[1], 0x84, "COSE_Sign1 is a four-element array");
    assert_eq!(&artifact[2..4], &[0x58, 0x56]);
    assert_eq!(&artifact[4..4 + 86], &protected[..]);
    assert_eq!(
        artifact[90], 0xa0,
        "the unprotected bucket is {{}} — spec §1.3"
    );
    assert_eq!(&artifact[91..93], &[0x58, 0x42]);
    assert_eq!(&artifact[93..93 + 66], &payload[..]);
    assert_eq!(&artifact[159..161], &[0x58, 0x40], "signature bstr head");
    assert_eq!(&artifact[161..], &from_hex(HEX_SIGNATURE)[..]);

    // The payload's own shape, spelled out from the spec table. The map head is
    // called out because `0xa4` is the one byte a regeneration from the
    // pre-`sequence` vector would most plausibly carry over unchanged.
    assert_eq!(payload[0], 0xa5, "five entries: sequence is label 5");
    // `sequence` is the last entry: label 5, then the shortest head that fits.
    // Derived from the NUMBER here, never copied from prose — a draft of the
    // spec wrote this encoding as `190130`, which is 304.
    let sequence_bytes = u16::try_from(SEQUENCE).unwrap().to_be_bytes();
    assert_eq!(
        &payload[payload.len() - 4..],
        &[0x05, 0x19, sequence_bytes[0], sequence_bytes[1]],
        "the frozen payload must end with label 5 and the canonical encoding of \
         {SEQUENCE}"
    );
    // And `not_before` immediately precedes it, with the eight-byte head its
    // value requires.
    assert!(NOT_BEFORE_UNIX_MS > u64::from(u32::MAX));
    let not_before_at = payload.len() - 4 - 9;
    assert_eq!(payload[not_before_at - 1], 0x04, "label 4");
    assert_eq!(payload[not_before_at], 0x1b, "eight-byte head");
    assert_eq!(
        &payload[not_before_at + 1..not_before_at + 9],
        &NOT_BEFORE_UNIX_MS.to_be_bytes()
    );
}

/// Both key derivations reach the vector's public keys.
///
/// If this fails, nothing below means anything — the two sides are not talking
/// about the same keys — so it is a test of its own rather than a preamble
/// inside another.
#[test]
fn the_seeds_derive_the_public_keys_the_vector_names() {
    let (_root_dir, root) = identity(&ROOT_SEED);
    let (_delegated_dir, delegated) = identity(&DELEGATED_SEED);
    assert_eq!(to_hex(&root.public_key_bytes()), HEX_ROOT_PUBLIC_KEY);
    assert_eq!(
        to_hex(&delegated.public_key_bytes()),
        HEX_DELEGATED_PUBLIC_KEY
    );
}

/// The `Sig_structure` this crate builds equals the one derived from the
/// specification with `openssl` and by hand.
#[test]
fn delegation_preimage_matches_the_frozen_sig_structure() {
    let (_root_dir, root) = identity(&ROOT_SEED);
    let (_delegated_dir, delegated) = identity(&DELEGATED_SEED);
    let claim = vector_claim(delegated.public_key_bytes());

    assert_eq!(
        claim.role.wire_value(),
        ROLE_WIRE_VALUE,
        "the role's wire encoding has moved; the vector was frozen at 1"
    );

    let preimage = delegation_preimage(&root.public_key_bytes(), &claim);
    assert_eq!(
        to_hex(&preimage),
        HEX_PREIMAGE,
        "the signing preimage no longer matches the frozen vector — every \
         signature ever produced under this format is over these bytes, so a \
         change here breaks all historical verification"
    );
}

/// The whole artifact, and the signature inside it, equal the frozen vector.
///
/// Ed25519 is deterministic, so `sign_delegation` under the vector's seed has
/// exactly one correct output; this is byte-identity, not mutual acceptance.
#[test]
fn sign_delegation_reproduces_the_frozen_artifact() {
    let (_root_dir, root) = identity(&ROOT_SEED);
    let (_delegated_dir, delegated) = identity(&DELEGATED_SEED);
    let claim = vector_claim(delegated.public_key_bytes());

    let artifact = sign_delegation(&root, &claim).unwrap();
    assert_eq!(to_hex(&artifact), HEX_ARTIFACT);

    // The signature on its own, so a failure says which half moved rather than
    // only that the artifact differs.
    assert_eq!(to_hex(&artifact[artifact.len() - 64..]), HEX_SIGNATURE);

    // And the two-phase path must reach the same bytes as the convenience
    // wrapper: an operator signing on an air-gapped machine gets the artifact a
    // single-machine signer would have produced, or the split is a second
    // format.
    let signature: [u8; 64] = from_hex(HEX_SIGNATURE).try_into().unwrap();
    let assembled = assemble_delegation(&root.public_key_bytes(), &claim, &signature).unwrap();
    assert_eq!(
        to_hex(&assembled),
        HEX_ARTIFACT,
        "assemble_delegation and sign_delegation disagree about the envelope"
    );
}

/// The positive control: the frozen bytes actually verify, and parse back to the
/// claim they were built from.
///
/// Without this, every assertion above could be satisfied by an implementation
/// broken in the same direction as the literals — the literals would then be
/// pinning a defect rather than a format.
#[test]
fn the_frozen_artifact_verifies_and_parses_back() {
    let (_root_dir, root) = identity(&ROOT_SEED);
    let (_delegated_dir, delegated) = identity(&DELEGATED_SEED);

    let root_public_key: [u8; 32] = from_hex(HEX_ROOT_PUBLIC_KEY).try_into().unwrap();
    let artifact = from_hex(HEX_ARTIFACT);

    let verified = verify_delegation(&artifact, &root_public_key, ORIGIN).unwrap();
    assert_eq!(verified.root_public_key, root_public_key);
    assert_eq!(verified.claim.origin, ORIGIN);
    assert_eq!(
        verified.claim.delegated_public_key,
        delegated.public_key_bytes()
    );
    assert_eq!(verified.claim.role, DelegationRole::Operational);
    assert_eq!(verified.claim.not_before_unix_ms, NOT_BEFORE_UNIX_MS);
    assert_eq!(verified.claim.sequence, SEQUENCE);
    assert_eq!(to_hex(&verified.signature), HEX_SIGNATURE);

    // Re-encoding the parsed delegation returns the same bytes, which is what
    // makes "canonical" mean the frozen encoding rather than merely a
    // self-consistent one.
    assert_eq!(to_hex(&verified.to_cose_bytes()), HEX_ARTIFACT);

    // The parse-only route reaches the same value. Named for parsing because it
    // is NOT verification: it takes no expected key and no expected origin, so
    // the delegation it returns vouches for nothing.
    let parsed = AnchorDelegation::from_cose_bytes(&artifact).unwrap();
    assert_eq!(parsed, verified);

    // And the identity the vector's seed produces is the one the artifact names,
    // so the frozen `kid` is not merely 32 plausible bytes.
    assert_eq!(root.public_key_bytes(), root_public_key);
}
