//! Stable refusal names selected independently of human explanations.

use lys_identity::IdentityError;
use lys_identity::grants::GrantError;

use crate::apps_error::AppError;
use crate::error::ServerError;
use crate::error_budget::BudgetError;
use crate::error_team::TeamError;
use crate::goals_types::GoalError;

impl ServerError {
    /// The stable refusal name, preserving any name supplied by an authority.
    pub fn name(&self) -> String {
        server(self).to_owned()
    }
}

fn server(error: &ServerError) -> &str {
    match error {
        ServerError::Team(error) => team(error),
        ServerError::Budget(error) => budget(error),
        ServerError::Call(error) => error.name(),
        ServerError::Holding(error) => error.name(),
        ServerError::Machine(error) => error.name(),
        ServerError::Cord(error) => error.name(),
        ServerError::Canvas(error) => error.name(),
        ServerError::HarnessCatalogueUnreadable { .. } => "harness_catalogue_unreadable",
        ServerError::Identity(error) => identity(error),
        ServerError::Grant(error) => grant(error),
        ServerError::App(error) => app(error),
        ServerError::Goal(error) => goal(error),
        ServerError::Inactive { .. } => "inactive",
        ServerError::NotSignedIn => "NotSignedIn",
        ServerError::NotAdmitted { .. } => "NotAdmitted",
        ServerError::NoPerson => "NoPerson",
        ServerError::SetupRequired => "SetupRequired",
        ServerError::AgentNotVisible => "AgentNotVisible",
        ServerError::GrantNotVisible => "GrantNotVisible",
        ServerError::Withheld { refusal, .. }
        | ServerError::SecretsRefused { refusal, .. }
        | ServerError::Runner { refusal, .. } => refusal,
        ServerError::SessionUnknown => "SessionUnknown",
        ServerError::SignInStateUnknown => "SignInStateUnknown",
        ServerError::SignInRefused => "SignInRefused",
        ServerError::SignInThrottled => "SignInThrottled",
        ServerError::RegistrationThrottled => "RegistrationThrottled",
        ServerError::SecondFactorUnsupported => "SecondFactorUnsupported",
        ServerError::SetupClosed => "SetupClosed",
        ServerError::SetupCodeRefused => "SetupCodeRefused",
        ServerError::SetupUnavailable { .. } => "SetupUnavailable",
        ServerError::AccountRefused { .. } => "AccountRefused",
        ServerError::SignInFailed { .. } => "SignInFailed",
        ServerError::ConfigInvalid { .. } => "ConfigInvalid",
        ServerError::BootstrapInterrupted { .. } => "BootstrapInterrupted",
        ServerError::RequestMalformed { .. } => "RequestMalformed",
        ServerError::BodyTooLarge => "BodyTooLarge",
        ServerError::SecretsUnavailable { .. } => "SecretsUnavailable",
        ServerError::RequestsUnavailable { .. } => "RequestsUnavailable",
        ServerError::McpRequestsUnavailable { .. } => "McpRequestsUnavailable",
        ServerError::McpServerUnknown { .. } => "mcp_server_unknown",
        ServerError::McpServerHeld { .. } => "mcp_server_held",
        ServerError::McpBeyondRemit { .. } => "mcp_beyond_remit",
        ServerError::RequestUnknown => "RequestUnknown",
        ServerError::RequestDecided { .. } => "RequestDecided",
        ServerError::RequestHeld { .. } => "RequestHeld",
        ServerError::RequestReused { .. } => "RequestReused",
        ServerError::NetworkUnavailable { .. } => "NetworkUnavailable",
        ServerError::LoginUnbound => "LoginUnbound",
        ServerError::MachineUnknown => "MachineUnknown",
        ServerError::SessionsUnavailable { .. } => "SessionsUnavailable",
        ServerError::MemoryUnavailable { .. } => "MemoryUnavailable",
        ServerError::ProvisioningUnavailable { .. } => "ProvisioningUnavailable",
        ServerError::ProvisioningChanged { .. } => "ProvisioningChanged",
        ServerError::ProvisioningReused { .. } => "ProvisioningReused",
        ServerError::ProfileVersionUnknown { .. } => "ProfileVersionUnknown",
        ServerError::ProfileVersionReplaced { .. } => "ProfileVersionReplaced",
        ServerError::ProfileNotReviewed { .. } => "ProfileNotReviewed",
        ServerError::CertificatesUnavailable { .. } => "CertificatesUnavailable",
        ServerError::CertificateUnknown { .. } => "CertificateUnknown",
        ServerError::CertificateReused { .. } => "CertificateReused",
        ServerError::CertificateWithdrawn { .. } => "CertificateWithdrawn",
        ServerError::RolesUnavailable { .. } => "RolesUnavailable",
        ServerError::RoleUnknown => "RoleUnknown",
        ServerError::RoleVersionUnknown => "RoleVersionUnknown",
        ServerError::HolderUnknown => "HolderUnknown",
        ServerError::RoleReused { .. } => "RoleReused",
        ServerError::RoleHeld { .. } => "RoleHeld",
        ServerError::HoldingOver { .. } => "HoldingOver",
        ServerError::HoldingChanged => "HoldingChanged",
        ServerError::LaunchRecordMissing => "LaunchRecordMissing",
        ServerError::OperatorRefused { .. } => "OperatorRefused",
        ServerError::AgentPassRefused { .. } => "AgentPassRefused",
        ServerError::AgentSignatureRefused { .. } => "AgentSignatureRefused",
        ServerError::AgentNotActive { .. } => "AgentNotActive",
        ServerError::MachineCannotReach { .. } => "MachineCannotReach",
        ServerError::MachineRetired => "MachineRetired",
        ServerError::MachineNotForAgent => "MachineNotForAgent",
        ServerError::MachineWithoutRuntime => "MachineWithoutRuntime",
        ServerError::WorkingFolderUnnamed => "WorkingFolderUnnamed",
        ServerError::MachineWithoutRunner => "MachineWithoutRunner",
        ServerError::SkillUnknown { .. } => "SkillUnknown",
        ServerError::PolicyUnrepresentable { .. } => "PolicyUnrepresentable",
        ServerError::ModelUnrepresentable { .. } => "ModelUnrepresentable",
        ServerError::HarnessUndeclared { .. } => "HarnessUndeclared",
        ServerError::LaunchUnrenderable { .. } => "LaunchUnrenderable",
        ServerError::McpCredentialInline { .. } => "McpCredentialInline",
        ServerError::McpSettingUnrepresentable { .. } => "McpSettingUnrepresentable",
        ServerError::McpHandleUnsupported { .. } => "McpHandleUnsupported",
        ServerError::RuntimeUnavailable { .. } => "RuntimeUnavailable",
        ServerError::RuntimeSessionUnknown => "RuntimeSessionUnknown",
        ServerError::RuntimeSessionStarted { .. } => "RuntimeSessionStarted",
        ServerError::RuntimeSessionStopped { .. } => "RuntimeSessionStopped",
        ServerError::RuntimeReportReused { .. } => "RuntimeReportReused",
        ServerError::ServiceAccountsUnavailable { .. } => "ServiceAccountsUnavailable",
        ServerError::ServiceAccountUnknown => "ServiceAccountUnknown",
        ServerError::ServiceAccountReused { .. } => "ServiceAccountReused",
        ServerError::ServiceAccountRetired { .. } => "ServiceAccountRetired",
        ServerError::ServiceAccountOwnerRetired { .. } => "ServiceAccountOwnerRetired",
        ServerError::PolicyUnavailable { .. } => "PolicyUnavailable",
        ServerError::AgentHasNoPolicy { .. } => "AgentHasNoPolicy",
        ServerError::PolicyVersionConflict { .. } => "PolicyVersionConflict",
        ServerError::PolicyRefused { refusal, .. } => refusal,
        ServerError::StopsUnavailable { .. } => "StopsUnavailable",
        ServerError::StopReused { .. } => "StopReused",
        ServerError::ReviewsUnavailable { .. } => "ReviewsUnavailable",
        ServerError::ReviewerOnly => "ReviewerOnly",
        ServerError::GrantNotDue { .. } => "GrantNotDue",
        ServerError::ReviewReused { .. } => "ReviewReused",
        ServerError::DirectoryUnavailable { .. } => "DirectoryUnavailable",
        ServerError::SignInProvidersUnavailable { .. } => "SignInProvidersUnavailable",
        ServerError::ProviderUnavailable { .. } => "ProviderUnavailable",
        ServerError::ClientUnknown => "ClientUnknown",
        ServerError::RedirectUnregistered => "RedirectUnregistered",
        ServerError::ScopeUnknown { .. } => "ScopeUnknown",
        ServerError::ScopeNotGranted { .. } => "ScopeNotGranted",
        ServerError::CodeUnknown => "CodeUnknown",
        ServerError::CodeUsed => "CodeUsed",
        ServerError::CodeExpired => "CodeExpired",
        ServerError::VerifierWrong => "VerifierWrong",
        ServerError::TokenUnknown => "TokenUnknown",
        ServerError::ProviderRefused { .. } => "ProviderRefused",
        ServerError::SignInProvidersRefused { .. } => "SignInProvidersRefused",
        ServerError::NotPermitted { .. } => "not_permitted",
        ServerError::NoLiveSession { .. } => "no_live_session",
        ServerError::RunnerAbsent { .. } => "runner_absent",
    }
}

fn identity(error: &IdentityError) -> &str {
    match error {
        IdentityError::DirectorySnapshotUnmigrated { .. } => "DirectorySnapshotUnmigrated",
        IdentityError::AnswersToUnknown { .. } => "AnswersToUnknown",
        IdentityError::AnswersToInactive { .. } => "AnswersToInactive",
        IdentityError::AnswersToCycle { .. } => "AnswersToCycle",
        IdentityError::NoAccountablePerson { .. } => "NoAccountablePerson",
        IdentityError::AlreadyBootstrapped { .. } => "AlreadyBootstrapped",
        IdentityError::RandomSourceUnavailable { .. } => "RandomSourceUnavailable",
        IdentityError::IdentifierMalformed { .. } => "IdentifierMalformed",
        IdentityError::BindingMalformed { .. } => "BindingMalformed",
        IdentityError::ProfileInvalid { .. } => "ProfileInvalid",
        IdentityError::ReasonRequired { .. } => "ReasonRequired",
        IdentityError::TransitionRefused { .. } => "TransitionRefused",
        IdentityError::ChangeMismatch { .. } => "ChangeMismatch",
        IdentityError::EventMalformed { .. } => "EventMalformed",
        IdentityError::EventNotCanonical => "EventNotCanonical",
        IdentityError::InstallEntry => "InstallEntry",
        IdentityError::VersionUnsupported { .. } => "VersionUnsupported",
        IdentityError::SignerMismatch => "SignerMismatch",
        IdentityError::SignatureInvalid => "SignatureInvalid",
        IdentityError::LogUnavailable { .. } => "LogUnavailable",
        IdentityError::LeafNotAnEvent { .. } => "LeafNotAnEvent",
        IdentityError::AppendUncertain { .. } => "AppendUncertain",
        IdentityError::AppendRefused { .. } => "AppendRefused",
        IdentityError::IdentityUnknown { .. } => "IdentityUnknown",
        IdentityError::AlreadyRegistered { .. } => "AlreadyRegistered",
        IdentityError::BindingTaken { .. } => "BindingTaken",
        IdentityError::StateMismatch { .. } => "StateMismatch",
        IdentityError::OperationReused { .. } => "OperationReused",
        IdentityError::LinkSourceSeen { .. } => "LinkSourceSeen",
        IdentityError::ReceiptInvalid { .. } => "ReceiptInvalid",
        IdentityError::KeyUnavailable { .. } => "KeyUnavailable",
        IdentityError::DraftHashMismatch => "DraftHashMismatch",
        IdentityError::DraftNotFound { .. } => "DraftNotFound",
        IdentityError::DraftNotPending { .. } => "DraftNotPending",
        IdentityError::DraftChangeInvalid { .. } => "DraftChangeInvalid",
        IdentityError::DraftEntry => "DraftEntry",
    }
}

fn grant(error: &GrantError) -> &str {
    match error {
        GrantError::GrantIdMalformed { .. } => "GrantIdMalformed",
        GrantError::TokenInvalid { .. } => "TokenInvalid",
        GrantError::ModelInvalid { .. } => "ModelInvalid",
        GrantError::RelationUnknown { .. } => "RelationUnknown",
        GrantError::ResourceKindUnheld { .. } => "ResourceKindUnheld",
        GrantError::ActionsOutside { .. } => "ActionsOutside",
        GrantError::AuthorityAbsent { .. } => "AuthorityAbsent",
        GrantError::PassOnOutside => "PassOnOutside",
        GrantError::WindowInvalid { .. } => "WindowInvalid",
        GrantError::LineageMalformed { .. } => "LineageMalformed",
        GrantError::MemberUnknown { .. } => "MemberUnknown",
        GrantError::MemberMissing { .. } => "MemberMissing",
        GrantError::RecipientKindUnknown { .. } => "RecipientKindUnknown",
        GrantError::GrantMalformed { .. } => "GrantMalformed",
        GrantError::GrantNotCanonical => "GrantNotCanonical",
        GrantError::SourceUnknown { .. } => "SourceUnknown",
        GrantError::LineageCycle { .. } => "LineageCycle",
        GrantError::IssuerNotHolder { .. } => "IssuerNotHolder",
        GrantError::NotHolder { .. } => "NotHolder",
        GrantError::ResourceOutside { .. } => "ResourceOutside",
        GrantError::UseOnly { .. } => "UseOnly",
        GrantError::RecipientRefused { .. } => "RecipientRefused",
        GrantError::WithheldFromAgents { .. } => "WithheldFromAgents",
        GrantError::PassOnBeyondSource { .. } => "PassOnBeyondSource",
        GrantError::ExpiryBeyondSource { .. } => "ExpiryBeyondSource",
        GrantError::ResponsibleMismatch { .. } => "ResponsibleMismatch",
        GrantError::IdentityNotActive { .. } => "IdentityNotActive",
        GrantError::Revoked { .. } => "Revoked",
        GrantError::Expired { .. } => "Expired",
        GrantError::NotStarted { .. } => "NotStarted",
        GrantError::RootAuthorityRefused { .. } => "RootAuthorityRefused",
        GrantError::RevokeRefused { .. } => "RevokeRefused",
        GrantError::AlreadyRevoked { .. } => "AlreadyRevoked",
        GrantError::GrantExists { .. } => "GrantExists",
        GrantError::NotHeld { .. } => "NotHeld",
        GrantError::OperationReused { .. } => "OperationReused",
        GrantError::EventMismatch { .. } => "EventMismatch",
        GrantError::GrantUnknown { .. } => "GrantUnknown",
        GrantError::EnvelopeMismatch { .. } => "EnvelopeMismatch",
        GrantError::EventMalformed { .. } => "EventMalformed",
        GrantError::EventNotCanonical => "EventNotCanonical",
        GrantError::VersionUnsupported { .. } => "VersionUnsupported",
        GrantError::SignerMismatch => "SignerMismatch",
        GrantError::SignatureInvalid => "SignatureInvalid",
        GrantError::ReceiptInvalid { .. } => "ReceiptInvalid",
        GrantError::LogUnavailable { .. } => "LogUnavailable",
        GrantError::LeafNotAnEvent { .. } => "LeafNotAnEvent",
        GrantError::AppendRefused { .. } => "AppendRefused",
        GrantError::OperationUnresolved { .. } => "OperationUnresolved",
        GrantError::ProjectionPending { .. } => "ProjectionPending",
        GrantError::StaleDecision { .. } => "StaleDecision",
        GrantError::PermissionEngineUnavailable { .. } => "PermissionEngineUnavailable",
        GrantError::PermissionAbsent { .. } => "PermissionAbsent",
        GrantError::Identity(error) => identity(error),
    }
}

fn app(error: &AppError) -> &str {
    match error {
        AppError::AppIdInvalid { .. } => "app_id_invalid",
        AppError::SchemaInvalid { .. } => "schema_invalid",
        AppError::AppExists { .. } => "app_exists",
        AppError::AppUnknown { .. } => "app_unknown",
        AppError::AppNotApproved { .. } => "app_not_approved",
        AppError::AppRetired { .. } => "app_retired",
        AppError::AppIsLys { .. } => "app_is_lys",
        AppError::AppDecided { .. } => "app_decided",
        AppError::AppOperationReused { .. } => "app_operation_reused",
        AppError::KindNotRegistered { .. } => "kind_not_registered",
        AppError::ActionNotDeclared { .. } => "action_not_declared",
        AppError::NotYourApp { .. } => "not_your_app",
        AppError::SchemaVersionMoved { .. } => "schema_version_moved",
        AppError::SchemaChangeStrandsGrants { .. } => "schema_change_strands_grants",
        AppError::SchemaVersionUnknown { .. } => "schema_version_unknown",
        AppError::SchemaChangePending { .. } => "schema_change_pending",
        AppError::RedirectInvalid { .. } | AppError::NoRedirect { .. } => "redirect_invalid",
        AppError::PlacementInvalid { .. } => "placement_invalid",
        AppError::CredentialRefused { .. } => "credential_refused",
        AppError::BenchUnknown => "bench_unknown",
        AppError::AppsUnavailable { .. } => "apps_unavailable",
    }
}

fn goal(error: &GoalError) -> &str {
    match error {
        GoalError::Unavailable { .. } => "goals_unavailable",
        GoalError::Unknown => "goal_unknown",
        GoalError::Reused { .. } => "goal_reused",
        GoalError::Closed { .. } => "goal_closed",
        GoalError::NotYourJudgement { .. } => "not_your_judgement",
        GoalError::ReminderNeedsDeadline => "reminder_needs_deadline",
        GoalError::WordsMalformed { .. } => "goal_words_malformed",
        GoalError::EvidenceMissing { .. } => "evidence_missing",
    }
}

fn team(error: &TeamError) -> &str {
    match error {
        TeamError::Unavailable { .. } => "TeamsUnavailable",
        TeamError::Unknown => "TeamUnknown",
        TeamError::Reused { .. } => "TeamReused",
        TeamError::Retired { .. } => "TeamRetired",
        TeamError::MemberHeld => "TeamMemberHeld",
        TeamError::MemberAbsent => "TeamMemberAbsent",
        TeamError::ParentCycle { .. } => "team_parent_cycle",
        TeamError::LeadNotMember { .. } => "team_lead_not_member",
        TeamError::MemberUnknown => "TeamMemberUnknown",
    }
}

fn budget(error: &BudgetError) -> &str {
    match error {
        BudgetError::BudgetsUnavailable { .. } => "BudgetsUnavailable",
        BudgetError::ConfigurationUnavailable { .. } => "ConfigurationUnavailable",
        BudgetError::ConfigurationVersionConflict { .. } => "ConfigurationVersionConflict",
        BudgetError::BudgetExhausted { .. } => "BudgetExhausted",
        BudgetError::BudgetVersionConflict { .. } => "BudgetVersionConflict",
        BudgetError::BudgetRefused { refusal, .. } => refusal,
    }
}
