//! The service's one `OpenAPI` document, `GET /openapi.json`, generated by
//! `lys-openapi` from the route table and the types the routes take and
//! answer. It is never written by hand.
//!
//! The table holds one entry per route the service serves: its method, its
//! path, its words, how a caller authenticates to it and the name of every
//! refusal it answers with. It is written in two places — `openapi_table.rs`
//! and `openapi_typed.rs` — and an entry of the first names its types in a
//! third, `openapi_types.rs`, which is looked up here by method and path.
//! Every schema is derived from the type the handler reads or writes, so the
//! document says what the code takes and answers and cannot say anything
//! else. `tests/openapi.rs` walks every route the source declares and every
//! entry here, and fails naming a route without an entry, an entry without a
//! route, a route that names no answer and is not on the list of routes whose
//! answer is open, and a body-taking route that names no body.

use std::borrow::Cow;
use std::sync::{Arc, OnceLock};

use axum::Router;
use axum::body::Bytes;
use axum::http::{HeaderValue, header};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use lys_openapi::{Api, Auth, Method, Route};
use serde_json::Value;

use crate::error::ServerError;
use crate::openapi_table::{E, TABLE};
use crate::openapi_typed::typed;
use crate::openapi_types::types;
use crate::routes::AppState;

/// One entry of the table, answering with every refusal of `refusals`'
/// sets once, and `NotSignedIn` when it has no public door, since
/// `signed_first.rs` answers that before the route is reached.
pub(crate) fn route(
    (method, path, summary): (Method, &'static str, &'static str),
    auth: &'static [Auth],
    request: Option<Cow<'static, str>>,
    response: Option<Cow<'static, str>>,
    refusals: &[&'static [&'static str]],
) -> Route {
    let mut named: Vec<&'static str> = Vec::new();
    let signed_first = (!auth.contains(&Auth::Public)).then_some(&["NotSignedIn"][..]);
    for name in refusals.iter().copied().chain(signed_first).flatten() {
        if !named.contains(name) {
            named.push(name);
        }
    }
    // The common ingress check can refuse any inactive authenticated caller.
    for refusal in ["inactive", "AnswersToInactive"] {
        if !named.contains(&refusal) {
            named.push(refusal);
        }
    }
    // The global admission guard refuses a bad operator header on every route.
    if !named.contains(&"OperatorRefused") {
        named.push("OperatorRefused");
    }
    Route {
        method,
        path,
        summary,
        auth,
        request,
        response,
        refusals: named,
    }
}

/// The route table: every route the service serves.
pub fn api() -> Api {
    let mut api = Api::new(
        "Lys directory",
        env!("CARGO_PKG_VERSION"),
        "Sign-in, identities, grants and the apps that register with Lys. Every refusal answers {refusal, reason, fields}.",
    );
    let named = types(&mut api);
    for E(method, path, summary, auth, refusals) in TABLE {
        let (request, response) = named.get(&(*method, path)).cloned().unwrap_or_default();
        api.route(route(
            (*method, path, summary),
            auth,
            request,
            response,
            refusals,
        ));
    }
    typed(&mut api);
    api
}

/// The document, generated from the table.
pub fn document() -> Result<Value, ServerError> {
    #[cfg(test)]
    cache_tests::built();
    let mut document = api()
        .document()
        .map_err(|faults| ServerError::ConfigInvalid {
            reason: format!(
                "the OpenAPI document could not be generated: {}",
                faults.join("; ")
            ),
        })?;
    crate::message_edges::document_query(&mut document)?;
    crate::list_page::document_query(&mut document)?;
    let answers_to = document
        .pointer_mut("/components/schemas/AgentRegistrationBody/properties/answers_to")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| ServerError::ConfigInvalid {
            reason: "the registration schema has no answers_to field".to_owned(),
        })?;
    answers_to.insert(
        "x-lys-answers-to".to_owned(),
        serde_json::json!(["person", "agent"]),
    );
    Ok(document)
}

/// The document's route: public, since the document describes the API and
/// grants nothing to whoever reads it.
pub fn routes() -> Router<Arc<AppState>> {
    Router::new().route("/openapi.json", get(served))
}

static DOCUMENT: OnceLock<Result<Bytes, String>> = OnceLock::new();

/// Validate and encode the document before any request is served.
pub(crate) fn prepare() -> Result<&'static Bytes, ServerError> {
    DOCUMENT
        .get_or_init(|| {
            let value = document().map_err(|error| error.to_string())?;
            encode(&value).map_err(|error| error.to_string())
        })
        .as_ref()
        .map_err(|reason| ServerError::ConfigInvalid {
            reason: reason.clone(),
        })
}

fn encode(value: &Value) -> Result<Bytes, ServerError> {
    let faults = lys_openapi::validate(value);
    if !faults.is_empty() {
        return Err(ServerError::ConfigInvalid {
            reason: format!("the OpenAPI document is invalid: {}", faults.join("; ")),
        });
    }
    serde_json::to_vec(value)
        .map(Bytes::from)
        .map_err(|error| ServerError::ConfigInvalid {
            reason: format!("the OpenAPI document could not be encoded: {error}"),
        })
}

async fn served() -> Result<Response, ServerError> {
    let mut answer = prepare()?.clone().into_response();
    answer.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    Ok(answer)
}

#[cfg(test)]
#[path = "openapi_cache_tests.rs"]
mod cache_tests;
