//! Test deployments: a copy of deploy/identity/config.example.toml on free
//! loopback ports, with its own compose project and state directory, torn
//! down with its volumes when dropped. Every credential is generated by the
//! real `lys identity prepare` for the test and discarded with it.

use std::error::Error;
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use super::compose;

/// The result every identity test and helper returns.
pub type TestResult<T = ()> = Result<T, Box<dyn Error>>;

/// The example configuration every test deployment starts from.
pub const EXAMPLE: &str = include_str!("../../../../deploy/identity/config.example.toml");

/// The repository root.
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// A loopback port nothing listens on now.
pub fn free_port() -> TestResult<u16> {
    Ok(TcpListener::bind("127.0.0.1:0")?.local_addr()?.port())
}

/// The loopback ports one deployment publishes.
#[derive(Debug, Clone, Copy)]
pub struct Ports {
    /// Rauthy's HTTP listener.
    pub rauthy: u16,
    /// The bundled `PostgreSQL` service.
    pub database: u16,
    /// `SpiceDB`'s gRPC listener.
    pub grpc: u16,
    /// `SpiceDB`'s HTTP listener.
    pub http: u16,
}

/// One isolated test deployment.
pub struct Deployment {
    /// The temporary directory holding the configuration and state.
    pub dir: tempfile::TempDir,
    /// The configuration file.
    pub config: PathBuf,
    /// The private state directory prepare writes.
    pub state: PathBuf,
    /// The compose project name.
    pub project: String,
    /// The published loopback ports.
    pub ports: Ports,
    /// Whether the bundled `PostgreSQL` service is used.
    pub bundled: bool,
}

impl Deployment {
    /// A deployment from the example configuration on fresh ports, with
    /// `edit` applied to the configuration text. Nothing is prepared or
    /// started yet.
    pub fn new(label: &str, edit: impl FnOnce(String) -> String) -> TestResult<Self> {
        let dir = tempfile::tempdir()?;
        let ports = Ports {
            rauthy: free_port()?,
            database: free_port()?,
            grpc: free_port()?,
            http: free_port()?,
        };
        let project = format!("lys-identity-test-{label}-{}", std::process::id());
        let text = EXAMPLE
            .replace(
                "project = \"lys-identity\"",
                &format!("project = \"{project}\""),
            )
            .replace("8480", &ports.rauthy.to_string())
            .replace("55432", &ports.database.to_string())
            .replace("50051", &ports.grpc.to_string())
            .replace("58443", &ports.http.to_string());
        let text = edit(text);
        let bundled = text.contains("bundled = true");
        let config = dir.path().join("identity.toml");
        std::fs::write(&config, text)?;
        let state = dir.path().join("state");
        Ok(Self {
            dir,
            config,
            state,
            project,
            ports,
            bundled,
        })
    }

    /// Writes another configuration beside this one, sharing its state
    /// directory, with `edit` applied to the current configuration text.
    pub fn variant(&self, name: &str, edit: impl FnOnce(String) -> String) -> TestResult<PathBuf> {
        let text = edit(std::fs::read_to_string(&self.config)?);
        let path = self.dir.path().join(format!("{name}.toml"));
        std::fs::write(&path, text)?;
        Ok(path)
    }

    /// Runs `lys identity <subcommand> --config <config>`.
    pub fn lys_with(&self, subcommand: &str, config: &Path) -> TestResult<Output> {
        Ok(Command::new(env!("CARGO_BIN_EXE_lys"))
            .args(["identity", subcommand, "--config"])
            .arg(config)
            .output()?)
    }

    /// Runs `lys identity <subcommand>` against this deployment.
    pub fn lys(&self, subcommand: &str) -> TestResult<Output> {
        self.lys_with(subcommand, &self.config)
    }

    /// Rauthy's loopback address.
    pub fn rauthy_address(&self) -> String {
        format!("127.0.0.1:{}", self.ports.rauthy)
    }

    /// `SpiceDB`'s loopback HTTP address.
    pub fn spicedb_address(&self) -> String {
        format!("127.0.0.1:{}", self.ports.http)
    }

    /// One generated credential, read from the state directory.
    pub fn secret(&self, file: &str) -> TestResult<String> {
        Ok(std::fs::read_to_string(self.state.join(file))?
            .trim_end()
            .to_string())
    }

    /// Every credential in the state directory: the generated ones and the
    /// client secrets configure stored.
    pub fn secrets(&self) -> TestResult<Vec<String>> {
        let mut secrets = Vec::new();
        for entry in std::fs::read_dir(&self.state)? {
            let name = entry?.file_name().to_string_lossy().into_owned();
            if name != "compose.env" && name != "configure-operations.json" {
                secrets.push(self.secret(&name)?);
            }
        }
        Ok(secrets)
    }
}

impl Drop for Deployment {
    fn drop(&mut self) {
        if let Err(error) = compose::down(self) {
            eprintln!("teardown of {} failed: {error}", self.project);
        }
    }
}

/// Stdout and stderr of a process, as text.
pub fn output_text(output: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

/// Refuses an unsuccessful process, carrying its output.
pub fn succeeded(output: &Output, what: &str) -> TestResult<()> {
    if output.status.success() {
        return Ok(());
    }
    Err(format!("{what} failed ({}): {}", output.status, output_text(output)).into())
}

/// Whether `text` holds any eight consecutive bytes of `secret`.
pub fn leaks(text: &str, secret: &str) -> bool {
    let bytes = secret.as_bytes();
    bytes.windows(8.min(bytes.len())).any(|window| {
        text.as_bytes()
            .windows(window.len())
            .any(|seen| seen == window)
    })
}
