#![cfg(test)]

//! Test deployments: a copy of deploy/identity/config.example.toml on free
//! loopback ports, with its own compose project and state directory, torn
//! down with its volumes when dropped. Every credential is generated by the
//! real `lys identity prepare` for the test and discarded with it.

use std::error::Error;
use std::fmt::Write as _;
use std::io::{Read, Seek, SeekFrom, Write};
use std::net::{Ipv4Addr, TcpListener};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use nix::fcntl::{Flock, FlockArg};

use super::compose;
use super::processes::output;

/// The result every identity test and helper returns.
pub type TestResult<T = ()> = Result<T, Box<dyn Error>>;

/// The example configuration every test deployment starts from.
pub const EXAMPLE: &str = include_str!("../../../../deploy/identity/config.example.toml");

/// The repository root.
pub fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

/// A loopback port nothing listens on now.
pub fn free_port() -> TestResult<u16> {
    Ok(TcpListener::bind("127.0.0.1:0")?.local_addr()?.port())
}

/// The first three parts of a private /24 range, as `172.29.N.`, that no
/// container network on this machine overlaps and no live test process
/// holds a claim on: a deployment's compose network, whose gateway is the
/// range's `.1`. Nextest runs every test in a process of its own, so the
/// claims are kept in one file every process reads and writes under an
/// exclusive lock; a claim lasts as long as the process that made it.
pub fn free_network() -> TestResult<String> {
    let listed = output(
        Command::new("docker").args(["network", "ls", "--quiet"]),
        "docker network ls",
    )?;
    succeeded(&listed, "docker network ls")?;
    let ids: Vec<String> = String::from_utf8_lossy(&listed.stdout)
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    let mut used = Vec::new();
    if !ids.is_empty() {
        let inspected = output(
            Command::new("docker")
                .args(["network", "inspect", "--format"])
                .arg("{{range .IPAM.Config}}{{.Subnet}} {{end}}")
                .args(&ids),
            "docker network inspect",
        )?;
        succeeded(&inspected, "docker network inspect")?;
        used.extend(
            String::from_utf8_lossy(&inspected.stdout)
                .split_whitespace()
                .filter_map(ipv4_range),
        );
    }
    let file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(false)
        .read(true)
        .write(true)
        .open(std::env::temp_dir().join("lys-identity-test-networks"))?;
    let mut claims_file = Flock::lock(file, FlockArg::LockExclusive)
        .map_err(|(_, errno)| format!("network_claims_unlocked: {errno}"))?;
    let mut text = String::new();
    claims_file.read_to_string(&mut text)?;
    let mut claims: Vec<(u64, u32)> = Vec::new();
    for line in text.lines() {
        if let Some((third, pid)) = line.split_once(' ')
            && let (Ok(third), Ok(pid)) = (third.parse(), pid.parse())
            && alive(pid)?
        {
            claims.push((third, pid));
        }
    }
    let base = u64::from(u32::from(Ipv4Addr::new(172, 29, 0, 0)));
    let chosen = (0..=255u64).find(|third| {
        let start = base | (third << 8);
        let overlaps = used
            .iter()
            .any(|&(first, end)| first < start + 256 && start < end);
        !overlaps && !claims.iter().any(|(claimed, _)| claimed == third)
    });
    let Some(third) = chosen else {
        return Err(
            "network_in_use: a container network or a live test overlaps every 172.29.N.0/24 range"
                .into(),
        );
    };
    claims.push((third, std::process::id()));
    let mut written = String::new();
    for (claimed, pid) in &claims {
        writeln!(written, "{claimed} {pid}")?;
    }
    claims_file.set_len(0)?;
    claims_file.seek(SeekFrom::Start(0))?;
    claims_file.write_all(written.as_bytes())?;
    Ok(format!("172.29.{third}."))
}

/// Whether process `pid` still runs: this process, or one `kill -0` reaches.
fn alive(pid: u32) -> TestResult<bool> {
    if pid == std::process::id() {
        return Ok(true);
    }
    let probed = output(
        Command::new("kill").args(["-0", &pid.to_string()]),
        &format!("kill -0 {pid}"),
    )?;
    Ok(probed.status.success())
}

/// The addresses an IPv4 range covers, first and one past the last.
fn ipv4_range(cidr: &str) -> Option<(u64, u64)> {
    let (address, prefix) = cidr.split_once('/')?;
    let first = u64::from(u32::from(address.parse::<Ipv4Addr>().ok()?));
    let prefix: u32 = prefix.parse().ok().filter(|prefix| *prefix <= 32)?;
    Some((first, first + (1u64 << (32 - prefix))))
}

/// The loopback ports one deployment publishes.
#[derive(Debug, Clone, Copy)]
pub struct Ports {
    /// Rauthy's HTTP listener.
    pub rauthy: u16,
    /// The bundled `PostgreSQL` service.
    pub database: u16,
    /// `SpiceDB`'s gRPC listener.
    pub grpc: u16,
    /// `SpiceDB`'s HTTP listener.
    pub http: u16,
}

/// One isolated test deployment.
pub struct Deployment {
    /// The temporary directory holding the configuration and state.
    pub dir: tempfile::TempDir,
    /// The configuration file.
    pub config: PathBuf,
    /// The private state directory prepare writes.
    pub state: PathBuf,
    /// The compose project name.
    pub project: String,
    /// The published loopback ports.
    pub ports: Ports,
    /// Whether the bundled `PostgreSQL` service is used.
    pub bundled: bool,
}

impl Deployment {
    /// A deployment from the example configuration on fresh ports, with
    /// `edit` applied to the configuration text. Nothing is prepared or
    /// started yet.
    pub fn new(label: &str, edit: impl FnOnce(String) -> String) -> TestResult<Self> {
        let dir = tempfile::tempdir()?;
        let ports = Ports {
            rauthy: free_port()?,
            database: free_port()?,
            grpc: free_port()?,
            http: free_port()?,
        };
        let project = format!("lys-identity-test-{label}-{}", std::process::id());
        let network = free_network()?;
        let text = EXAMPLE
            .replace(
                "project = \"lys-identity\"",
                &format!("project = \"{project}\""),
            )
            .replace("8480", &ports.rauthy.to_string())
            .replace("55432", &ports.database.to_string())
            .replace("58051", &ports.grpc.to_string())
            .replace("58443", &ports.http.to_string())
            .replace("172.29.48.", &network);
        let text = edit(text);
        let bundled = database_bundled(&text)?;
        let config = dir.path().join("identity.toml");
        std::fs::write(&config, text)?;
        let state = dir.path().join("state");
        Ok(Self {
            dir,
            config,
            state,
            project,
            ports,
            bundled,
        })
    }

    /// Writes another configuration beside this one, sharing its state
    /// directory, with `edit` applied to the current configuration text.
    pub fn variant(&self, name: &str, edit: impl FnOnce(String) -> String) -> TestResult<PathBuf> {
        let text = edit(std::fs::read_to_string(&self.config)?);
        let path = self.dir.path().join(format!("{name}.toml"));
        std::fs::write(&path, text)?;
        Ok(path)
    }

    /// Runs `lys identity <subcommand> --config <config>`.
    pub fn lys_with(&self, subcommand: &str, config: &Path) -> TestResult<Output> {
        output(
            Command::new(env!("CARGO_BIN_EXE_lys"))
                .args(["identity", subcommand, "--config"])
                .arg(config),
            &format!("lys identity {subcommand}"),
        )
    }

    /// Runs `lys identity <subcommand>` against this deployment.
    pub fn lys(&self, subcommand: &str) -> TestResult<Output> {
        self.lys_with(subcommand, &self.config)
    }

    /// Rauthy's loopback address.
    pub fn rauthy_address(&self) -> String {
        format!("127.0.0.1:{}", self.ports.rauthy)
    }

    /// `SpiceDB`'s loopback HTTP address.
    pub fn spicedb_address(&self) -> String {
        format!("127.0.0.1:{}", self.ports.http)
    }

    /// One generated credential, read from the state directory.
    pub fn secret(&self, file: &str) -> TestResult<String> {
        Ok(std::fs::read_to_string(self.state.join(file))?
            .trim_end()
            .to_string())
    }

    /// Every credential in the state directory: the generated ones and the
    /// client secrets configure stored.
    pub fn secrets(&self) -> TestResult<Vec<String>> {
        let mut secrets = Vec::new();
        for entry in std::fs::read_dir(&self.state)? {
            let name = entry?.file_name().to_string_lossy().into_owned();
            if name != "compose.env" && name != "configure-operations.json" {
                secrets.push(self.secret(&name)?);
            }
        }
        Ok(secrets)
    }
}

impl Drop for Deployment {
    fn drop(&mut self) {
        if let Err(error) = compose::down(self) {
            eprintln!("teardown of {} failed: {error}", self.project);
        }
    }
}

/// The `[database]` table's `bundled` value, read as TOML so a comment that
/// mentions the setting is never taken for it.
fn database_bundled(text: &str) -> TestResult<bool> {
    let config: toml::Table = toml::from_str(text)?;
    config
        .get("database")
        .and_then(|database| database.get("bundled"))
        .and_then(toml::Value::as_bool)
        .ok_or_else(|| "config_invalid: no boolean database.bundled".into())
}

/// Stdout and stderr of a process, as text.
pub fn output_text(output: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

/// Refuses an unsuccessful process, carrying its output.
pub fn succeeded(output: &Output, what: &str) -> TestResult<()> {
    if output.status.success() {
        return Ok(());
    }
    Err(format!("{what} failed ({}): {}", output.status, output_text(output)).into())
}

/// Whether `text` holds any eight consecutive bytes of `secret`.
pub fn leaks(text: &str, secret: &str) -> bool {
    let bytes = secret.as_bytes();
    bytes.windows(8.min(bytes.len())).any(|window| {
        text.as_bytes()
            .windows(window.len())
            .any(|seen| seen == window)
    })
}
