//! The typed deployment configuration `lys identity` reads, and its
//! validation. The file holds addresses and names only; every secret is
//! generated by `prepare` into the venue. Diagnostics name keys and values
//! from this file, which is safe because none of its values is a secret.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use super::error::{IdentityError, IdentityResult};

/// The whole configuration file.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeployConfig {
    /// Where the private files go: absolute, or relative to the config file.
    pub venue: PathBuf,
    /// The `PostgreSQL` service and database.
    pub database: DatabaseConfig,
    /// Rauthy's public origin, relying party and first administrator.
    pub rauthy: RauthyConfig,
    /// `SpiceDB`'s published ports.
    pub spicedb: SpicedbConfig,
    /// The host ports the compose file publishes.
    pub ports: PortsConfig,
    /// The two OIDC clients `configure` registers.
    pub clients: ClientsConfig,
    /// Where the theme mapping lives.
    #[serde(default)]
    pub themes: ThemesConfig,
}

/// The `PostgreSQL` service and the one identity database.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DatabaseConfig {
    /// The host as the services reach it: the compose `postgres` service, or
    /// a network device.
    pub host: String,
    /// The port on that host.
    pub port: u16,
    /// The database name.
    pub name: String,
    /// The administrative role `PostgreSQL`'s init runs as.
    pub admin_role: String,
    /// The address the operator's host reaches the same database on, when it
    /// differs from `host:port` (the compose service is published on a host
    /// port). Absent, health dials `host:port`.
    #[serde(default)]
    pub reach: Option<String>,
}

/// Rauthy's public origin and the `WebAuthn` relying party.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RauthyConfig {
    /// `http` or `https`.
    pub scheme: String,
    /// The host and port a browser reaches Rauthy on, with no scheme.
    pub public_url: String,
    /// The `WebAuthn` relying party id: the host of `public_url`.
    pub rp_id: String,
    /// The `WebAuthn` relying party origin: the full origin of `public_url`.
    pub rp_origin: String,
    /// The first administrator's email.
    pub admin_email: String,
}

/// `SpiceDB`'s published ports.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpicedbConfig {
    /// The `gRPC` port on the operator's host.
    pub grpc_port: u16,
    /// The HTTP gateway port on the operator's host.
    pub http_port: u16,
}

/// The host ports the compose file publishes for the other two.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PortsConfig {
    /// `PostgreSQL`'s host port.
    pub postgres: u16,
    /// Rauthy's host port.
    pub rauthy: u16,
}

/// The two clients.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientsConfig {
    /// The platform's own confidential client, with S256.
    pub platform: ClientConfig,
    /// Cambium's client, RS256 for its verifier.
    pub cambium: ClientConfig,
}

/// One OIDC client.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientConfig {
    /// The client id Rauthy knows it by.
    pub id: String,
    /// The exact redirect URIs.
    pub redirect_uris: Vec<String>,
}

/// Where the theme mapping lives.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ThemesConfig {
    /// The mapping file, relative to the config file: the repository's
    /// `deploy/identity/rauthy-themes.json` by default.
    pub file: PathBuf,
}

impl Default for ThemesConfig {
    fn default() -> Self {
        Self {
            file: PathBuf::from("rauthy-themes.json"),
        }
    }
}

impl DeployConfig {
    /// Read and validate the configuration at `path`. Relative paths inside
    /// it are resolved against the file's own directory.
    pub fn load(path: &Path) -> IdentityResult<Self> {
        let text = std::fs::read_to_string(path).map_err(|source| IdentityError::Io {
            operation: "read the configuration",
            path: path.to_path_buf(),
            source,
        })?;
        let mut config: Self = toml::from_str(&text).map_err(|error| IdentityError::Config {
            operation: "read the configuration",
            path: path.to_path_buf(),
            detail: error.to_string(),
        })?;
        let base = path.parent().unwrap_or_else(|| Path::new("."));
        if config.venue.is_relative() {
            config.venue = base.join(&config.venue);
        }
        if config.themes.file.is_relative() {
            config.themes.file = base.join(&config.themes.file);
        }
        config.validate(path)?;
        Ok(config)
    }

    /// The rules every value has to satisfy before a service is written for.
    fn validate(&self, path: &Path) -> IdentityResult<()> {
        let refuse = |detail: String| IdentityError::Config {
            operation: "validate the configuration",
            path: path.to_path_buf(),
            detail,
        };
        if self.rauthy.scheme != "http" && self.rauthy.scheme != "https" {
            return Err(refuse(format!(
                "rauthy.scheme must be http or https, not {}",
                self.rauthy.scheme
            )));
        }
        if self.rauthy.public_url.contains("://") || self.rauthy.public_url.is_empty() {
            return Err(refuse(
                "rauthy.public_url is the host and port only, with no scheme".to_string(),
            ));
        }
        let origin = format!("{}://{}", self.rauthy.scheme, self.rauthy.public_url);
        if self.rauthy.rp_origin != origin {
            return Err(refuse(format!(
                "rauthy.rp_origin must be the origin of public_url, {origin}, not {}",
                self.rauthy.rp_origin
            )));
        }
        let host = self
            .rauthy
            .public_url
            .rsplit_once(':')
            .map_or(self.rauthy.public_url.as_str(), |(host, _)| host);
        if self.rauthy.rp_id != host {
            return Err(refuse(format!(
                "rauthy.rp_id must be the host of public_url, {host}, not {}",
                self.rauthy.rp_id
            )));
        }
        if !self.rauthy.admin_email.contains('@') {
            return Err(refuse(
                "rauthy.admin_email must be an email address".to_string(),
            ));
        }
        for name in ["database.host", "database.name", "database.admin_role"] {
            let value = match name {
                "database.host" => &self.database.host,
                "database.name" => &self.database.name,
                _ => &self.database.admin_role,
            };
            if value.trim().is_empty() {
                return Err(refuse(format!("{name} must not be empty")));
            }
        }
        for (name, client) in [
            ("clients.platform", &self.clients.platform),
            ("clients.cambium", &self.clients.cambium),
        ] {
            if client.id.len() < 2 {
                return Err(refuse(format!("{name}.id must be at least two characters")));
            }
            if client.redirect_uris.is_empty() {
                return Err(refuse(format!(
                    "{name}.redirect_uris must name at least one URI"
                )));
            }
            for uri in &client.redirect_uris {
                if !uri.starts_with("http://") && !uri.starts_with("https://") {
                    return Err(refuse(format!(
                        "{name}.redirect_uris holds {uri}, which is not an http or https URI"
                    )));
                }
            }
        }
        if self.clients.platform.id == self.clients.cambium.id {
            return Err(refuse(
                "the two clients must have different ids".to_string(),
            ));
        }
        Ok(())
    }

    /// Rauthy's base URL as the operator reaches it.
    #[must_use]
    pub fn rauthy_origin(&self) -> String {
        format!("{}://{}", self.rauthy.scheme, self.rauthy.public_url)
    }

    /// The address health dials for the database.
    #[must_use]
    pub fn database_reach(&self) -> String {
        self.database
            .reach
            .clone()
            .unwrap_or_else(|| format!("{}:{}", self.database.host, self.database.port))
    }

    /// `SpiceDB`'s HTTP gateway as the operator reaches it.
    #[must_use]
    pub fn spicedb_http_origin(&self) -> String {
        format!("http://localhost:{}", self.spicedb.http_port)
    }
}
