//! Typed deployment configuration for `lys identity`, and its validation.
//!
//! Invariants:
//!
//! - A [`DeploymentConfig`] only exists validated: [`DeploymentConfig::load`]
//!   parses and then refuses every value the deployment cannot use, by name,
//!   before anything is written or sent.
//! - The configuration holds no secret. Every credential is generated by
//!   `prepare` into the state directory, so a diagnostic may quote a
//!   configuration value without disclosing anything.
//! - The database address is configuration (ADR-005). The host `postgres`
//!   names the compose file's own `PostgreSQL` service; any other host is an
//!   external database, and nothing substitutes a local address for it.
//! - Exactly two clients are managed, platform and Cambium, and neither may
//!   take the id of Rauthy's built-in `rauthy` client.

use std::net::{Ipv4Addr, SocketAddrV4};
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::identity::error::{IdentityError, IdentityResult};

/// The database host that selects the compose file's own `PostgreSQL` service.
pub const LOCAL_DATABASE_HOST: &str = "postgres";

/// The id of the client Rauthy's own migration inserts. Never managed.
pub const BUILTIN_CLIENT_ID: &str = "rauthy";

/// The whole deployment configuration file.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeploymentConfig {
    /// Compose project and state directory.
    pub deployment: DeploymentSection,
    /// The one `PostgreSQL` database.
    pub database: DatabaseSection,
    /// Rauthy's origins and bootstrap administrator.
    pub rauthy: RauthySection,
    /// `SpiceDB`'s published addresses.
    pub spicedb: SpicedbSection,
    /// The two managed clients.
    pub clients: ClientsSection,
    /// The directory holding the configuration file; relative paths resolve
    /// against it.
    #[serde(skip)]
    pub base_dir: PathBuf,
}

/// `[deployment]`.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeploymentSection {
    /// The compose project name.
    pub compose_project: String,
    /// Where prepare writes private files, relative to the config file.
    pub state_dir: PathBuf,
}

/// `[database]`.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DatabaseSection {
    /// The host Rauthy and `SpiceDB` connect to.
    pub host: String,
    /// The port they connect to.
    pub port: u16,
    /// The database name.
    pub name: String,
    /// TLS to the database.
    pub tls: DatabaseTls,
    /// Where the local `PostgreSQL` service is published on this node.
    pub local_publish: String,
}

/// TLS to the database.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DatabaseTls {
    /// Plain connections; for the local service only.
    Disable,
    /// TLS required.
    Require,
}

/// `[rauthy]`.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RauthySection {
    /// The issuer origin, scheme and authority only.
    pub public_origin: String,
    /// Reverse proxies trusted in proxy mode (TLS origin).
    pub trusted_proxies: Vec<String>,
    /// Where Rauthy's listener is published on this node.
    pub publish: String,
    /// The bootstrap administrator's address.
    pub admin_email: String,
}

/// `[spicedb]`.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpicedbSection {
    /// `SpiceDB`'s HTTP gateway, which serves readiness.
    pub http_publish: String,
    /// `SpiceDB`'s `gRPC` API.
    pub grpc_publish: String,
}

/// `[clients]`: exactly the platform and Cambium clients.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientsSection {
    /// The identity platform's own client.
    pub platform: ClientConfig,
    /// Cambium's client.
    pub cambium: ClientConfig,
}

/// One managed OIDC client.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientConfig {
    /// Rauthy client id.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Exact redirect URIs.
    pub redirect_uris: Vec<String>,
    /// Exact post-logout redirect URIs.
    pub post_logout_redirect_uris: Vec<String>,
    /// Token signing algorithm.
    pub signing_alg: SigningAlg,
    /// Whether PKCE S256 is required.
    pub pkce_s256: bool,
}

/// A token signing algorithm Rauthy offers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum SigningAlg {
    /// RSASSA-PKCS1-v1_5 with SHA-256.
    RS256,
    /// Ed25519.
    EdDSA,
}

impl SigningAlg {
    /// The name Rauthy's API uses.
    pub fn as_str(self) -> &'static str {
        match self {
            SigningAlg::RS256 => "RS256",
            SigningAlg::EdDSA => "EdDSA",
        }
    }
}

/// The two roles a managed client plays; the themes are keyed by role.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClientRole {
    /// The identity platform's own client (the identity orange).
    Platform,
    /// Cambium's client (Cambium green).
    Cambium,
}

impl ClientRole {
    /// The role's key in the configuration and the theme mapping.
    pub fn key(self) -> &'static str {
        match self {
            ClientRole::Platform => "platform",
            ClientRole::Cambium => "cambium",
        }
    }
}

/// An absolute URI split at its authority. Only what validation needs.
struct UriParts<'a> {
    scheme: &'a str,
    host: &'a str,
    port: Option<u16>,
    rest: &'a str,
}

impl DeploymentConfig {
    /// Read, parse and validate the configuration at `path`.
    pub fn load(path: &Path) -> IdentityResult<Self> {
        let text =
            std::fs::read_to_string(path).map_err(|source| IdentityError::ConfigUnreadable {
                path: path.to_path_buf(),
                source,
            })?;
        let mut config: Self =
            toml::from_str(&text).map_err(|error| IdentityError::ConfigInvalid {
                path: path.to_path_buf(),
                reason: error.message().to_string(),
            })?;
        config.base_dir = match path.parent() {
            Some(parent) if !parent.as_os_str().is_empty() => parent.to_path_buf(),
            _ => PathBuf::from("."),
        };
        config.validate()?;
        Ok(config)
    }

    /// The state directory, resolved against the configuration file.
    pub fn state_dir(&self) -> PathBuf {
        self.base_dir.join(&self.deployment.state_dir)
    }

    /// Whether the compose file's own `PostgreSQL` service is the database.
    pub fn uses_local_database(&self) -> bool {
        self.database.host == LOCAL_DATABASE_HOST
    }

    /// Where health reaches `PostgreSQL` from this node: the local service's
    /// published address, or the external host itself. Never a default.
    pub fn database_probe(&self) -> String {
        if self.uses_local_database() {
            self.database.local_publish.clone()
        } else {
            format!("{}:{}", self.database.host, self.database.port)
        }
    }

    /// The issuer Rauthy serves: the public origin followed by `/auth/v1/`.
    pub fn issuer(&self) -> String {
        format!("{}/auth/v1/", self.rauthy.public_origin)
    }

    /// Rauthy's `PUB_URL`: the public origin's authority.
    pub fn pub_url(&self) -> IdentityResult<String> {
        let parts = self.origin_parts()?;
        Ok(match parts.port {
            Some(port) => format!("{}:{port}", parts.host),
            None => parts.host.to_string(),
        })
    }

    /// The `WebAuthn` relying-party id: the public origin's host.
    pub fn rp_id(&self) -> IdentityResult<String> {
        Ok(self.origin_parts()?.host.to_string())
    }

    /// Whether the public origin is a TLS origin behind a reverse proxy.
    pub fn proxy_mode(&self) -> IdentityResult<bool> {
        Ok(self.origin_parts()?.scheme == "https")
    }

    /// The two managed clients with their roles, platform first.
    pub fn managed_clients(&self) -> [(ClientRole, &ClientConfig); 2] {
        [
            (ClientRole::Platform, &self.clients.platform),
            (ClientRole::Cambium, &self.clients.cambium),
        ]
    }

    fn origin_parts(&self) -> IdentityResult<UriParts<'_>> {
        split_uri(&self.rauthy.public_origin).map_err(|reason| IdentityError::InvalidIssuer {
            field: "rauthy.public_origin",
            value: self.rauthy.public_origin.clone(),
            reason,
        })
    }

    fn validate(&self) -> IdentityResult<()> {
        check_chars(
            "deployment.compose_project",
            &self.deployment.compose_project,
            1,
            63,
            |c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_',
            "must be 1 to 63 lowercase letters, digits, '-' or '_'",
        )?;
        if self.deployment.state_dir.as_os_str().is_empty() {
            return Err(invalid("deployment.state_dir", "", "must not be empty"));
        }
        check_chars(
            "database.host",
            &self.database.host,
            1,
            253,
            |c| c.is_ascii_alphanumeric() || c == '.' || c == '-',
            "must be a host name or IPv4 address",
        )?;
        if self.database.port == 0 {
            return Err(invalid("database.port", "0", "must be a port from 1 to 65535"));
        }
        check_chars(
            "database.name",
            &self.database.name,
            1,
            63,
            |c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_',
            "must be 1 to 63 lowercase letters, digits or '_'",
        )?;
        check_publish("database.local_publish", &self.database.local_publish)?;
        check_publish("rauthy.publish", &self.rauthy.publish)?;
        check_publish("spicedb.http_publish", &self.spicedb.http_publish)?;
        check_publish("spicedb.grpc_publish", &self.spicedb.grpc_publish)?;
        self.validate_origin()?;
        check_email(&self.rauthy.admin_email)?;
        for (role, client) in self.managed_clients() {
            validate_client(role, client)?;
        }
        if self.clients.platform.id == self.clients.cambium.id {
            return Err(IdentityError::DuplicateClientId {
                id: self.clients.platform.id.clone(),
            });
        }
        Ok(())
    }

    fn validate_origin(&self) -> IdentityResult<()> {
        let origin = &self.rauthy.public_origin;
        let issuer = |reason| IdentityError::InvalidIssuer {
            field: "rauthy.public_origin",
            value: origin.clone(),
            reason,
        };
        let parts = self.origin_parts()?;
        if parts.scheme != "http" && parts.scheme != "https" {
            return Err(issuer("the scheme must be http or https"));
        }
        if !parts.rest.is_empty() {
            return Err(issuer("an origin carries no path, query or fragment"));
        }
        if parts.scheme == "http" && !is_loopback(parts.host) {
            return Err(issuer("an http origin is accepted only on a loopback host"));
        }
        if parts.scheme == "https" && self.rauthy.trusted_proxies.is_empty() {
            return Err(invalid(
                "rauthy.trusted_proxies",
                "",
                "a TLS origin is served through a reverse proxy, which must be listed",
            ));
        }
        for proxy in &self.rauthy.trusted_proxies {
            check_chars(
                "rauthy.trusted_proxies",
                proxy,
                1,
                64,
                |c| c.is_ascii_hexdigit() || c == '.' || c == ':' || c == '/',
                "must be an IP address or CIDR range",
            )?;
        }
        Ok(())
    }
}

fn validate_client(role: ClientRole, client: &ClientConfig) -> IdentityResult<()> {
    let key = role.key();
    if client.id == BUILTIN_CLIENT_ID {
        return Err(IdentityError::BuiltinClientReserved {
            field: format!("clients.{key}.id"),
        });
    }
    check_chars(
        &format!("clients.{key}.id"),
        &client.id,
        2,
        256,
        |c| c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-',
        "must be 2 to 256 letters, digits, '.', '_' or '-'",
    )?;
    check_chars(
        &format!("clients.{key}.name"),
        &client.name,
        2,
        128,
        |c| c.is_ascii_alphanumeric() || c == ' ' || c == '-',
        "must be 2 to 128 letters, digits, spaces or '-'",
    )?;
    if client.redirect_uris.is_empty() {
        return Err(IdentityError::InvalidRedirectUri {
            field: format!("clients.{key}.redirect_uris"),
            value: String::new(),
            reason: "at least one exact redirect URI is required",
        });
    }
    for uri in &client.redirect_uris {
        check_redirect(&format!("clients.{key}.redirect_uris"), uri)?;
    }
    for uri in &client.post_logout_redirect_uris {
        check_redirect(&format!("clients.{key}.post_logout_redirect_uris"), uri)?;
    }
    Ok(())
}

fn check_redirect(field: &str, uri: &str) -> IdentityResult<()> {
    let refuse = |reason| IdentityError::InvalidRedirectUri {
        field: field.to_string(),
        value: uri.to_string(),
        reason,
    };
    let parts = split_uri(uri).map_err(refuse)?;
    if parts.scheme != "http" && parts.scheme != "https" {
        return Err(refuse("the scheme must be http or https"));
    }
    if parts.scheme == "http" && !is_loopback(parts.host) {
        return Err(refuse("an http redirect URI is accepted only on a loopback host"));
    }
    if uri.contains('#') {
        return Err(refuse("a redirect URI carries no fragment"));
    }
    if uri.contains('*') {
        return Err(refuse("a redirect URI is exact; wildcards are refused"));
    }
    if !(parts.rest.is_empty() || parts.rest.starts_with('/') || parts.rest.starts_with('?')) {
        return Err(refuse("the authority must be followed by a path or query"));
    }
    let allowed = |c: char| c.is_ascii_alphanumeric() || ",.:/_-&?=~!$'()+%@".contains(c);
    if !uri.chars().all(allowed) {
        return Err(refuse("contains a character Rauthy does not accept in a URI"));
    }
    Ok(())
}

fn split_uri(value: &str) -> Result<UriParts<'_>, &'static str> {
    let (scheme, after) = value
        .split_once("://")
        .ok_or("not an absolute URI with a scheme and authority")?;
    let end = after.find(['/', '?', '#']).unwrap_or(after.len());
    let (authority, rest) = after.split_at(end);
    if authority.contains('@') {
        return Err("user information in the authority is refused");
    }
    if authority.contains('[') {
        return Err("IPv6 literal hosts are not supported");
    }
    let (host, port) = match authority.split_once(':') {
        Some((host, port)) => {
            let port = port
                .parse::<u16>()
                .ok()
                .filter(|port| *port != 0)
                .ok_or("the port must be a number from 1 to 65535")?;
            (host, Some(port))
        }
        None => (authority, None),
    };
    let host_ok = !host.is_empty()
        && host
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-');
    if !host_ok {
        return Err("the host must be a host name or IPv4 address");
    }
    Ok(UriParts {
        scheme,
        host,
        port,
        rest,
    })
}

fn is_loopback(host: &str) -> bool {
    host == "localhost"
        || host
            .parse::<Ipv4Addr>()
            .is_ok_and(|address| address.is_loopback())
}

fn check_publish(field: &str, value: &str) -> IdentityResult<()> {
    match value.parse::<SocketAddrV4>() {
        Ok(address) if address.port() != 0 => Ok(()),
        _ => Err(invalid(
            field,
            value,
            "must be an IPv4 address and port, e.g. 127.0.0.1:8080",
        )),
    }
}

fn check_email(value: &str) -> IdentityResult<()> {
    let field = "rauthy.admin_email";
    let local_ok = |c: char| c.is_ascii_alphanumeric() || "._+-".contains(c);
    let domain_ok = |c: char| c.is_ascii_alphanumeric() || ".-".contains(c);
    match value.split_once('@') {
        Some((local, domain))
            if !local.is_empty()
                && domain.contains('.')
                && local.chars().all(local_ok)
                && domain.chars().all(domain_ok) =>
        {
            Ok(())
        }
        _ => Err(invalid(field, value, "must be a plain address, e.g. admin@identity.test")),
    }
}

fn check_chars(
    field: &str,
    value: &str,
    min: usize,
    max: usize,
    allowed: impl Fn(char) -> bool,
    reason: &'static str,
) -> IdentityResult<()> {
    let length = value.chars().count();
    if length < min || length > max || !value.chars().all(allowed) {
        return Err(invalid(field, value, reason));
    }
    Ok(())
}

fn invalid(field: &str, value: &str, reason: &'static str) -> IdentityError {
    IdentityError::InvalidConfigValue {
        field: field.to_string(),
        value: value.to_string(),
        reason,
    }
}

#[cfg(test)]
#[path = "config_tests.rs"]
mod tests;
