/** The bare buttons still standing outside the act control (shell/Act.tsx), file by file, counted from the source on
 *  6 October 2026. A number here goes down in the commit that moves those buttons to the control, and its line goes
 *  when it reaches none. Nothing is added and no number is raised: a new act is an `Act`. */
export const STANDING: Record<string, number> = {
  'features/access/Access.tsx': 1,
  'features/access/Graph.tsx': 4,
  'features/apps/Apps.tsx': 10,
  'features/apps/SaveCredentials.tsx': 1,
  'features/apps/SchemaBench.tsx': 3,
  'features/apps/SchemaBuilder.tsx': 7,
  'features/connections/SignInProviders.tsx': 3,
  'features/dashboard/AgentTree.tsx': 5,
  'features/dashboard/Dashboard.tsx': 2,
  'features/dashboard/StopEverything.tsx': 5,
  'features/drafts/Drafts.tsx': 6,
  'features/file/AgentOverview.tsx': 1,
  'features/file/CertificateChanges.tsx': 4,
  'features/file/DropHandle.tsx': 3,
  'features/file/EmergencyStop.tsx': 3,
  'features/file/HeadMenu.tsx': 2,
  'features/file/IdentityFile.tsx': 1,
  'features/file/PersonalBudgets.tsx': 1,
  'features/file/sections.tsx': 3,
  'features/grants/CheckBox.tsx': 1,
  'features/grants/Delegate.tsx': 2,
  'features/grants/GrantTable.tsx': 2,
  'features/grants/Revoke.tsx': 2,
  'features/import/EstateApproval.tsx': 1,
  'features/network/AddMachine.tsx': 5,
  'features/network/ComputerAdmission.tsx': 2,
  'features/network/JoinCode.tsx': 4,
  'features/network/MachineDetail.tsx': 4,
  'features/network/Network.tsx': 3,
  'features/people/Account.tsx': 2,
  'features/people/AddAgent.tsx': 1,
  'features/people/AddPerson.tsx': 1,
  'features/people/People.tsx': 1,
  'features/people/RecordedForm.tsx': 2,
  'features/provisioning/FolderChooser.tsx': 5,
  'features/provisioning/Given.tsx': 2,
  'features/provisioning/McpServers.tsx': 2,
  'features/provisioning/Permissions.tsx': 6,
  'features/provisioning/SaveSettings.tsx': 1,
  'features/proxy/ProxyView.tsx': 2,
  'features/requests/AskForm.tsx': 3,
  'features/requests/DecisionForm.tsx': 5,
  'features/requests/HeldApproval.tsx': 1,
  'features/requests/Requests.tsx': 2,
  'features/reviews/KeepGrant.tsx': 3,
  'features/reviews/Reviews.tsx': 1,
  'features/roles/ChangeStatus.tsx': 1,
  'features/roles/RoleEditor.tsx': 3,
  'features/roles/RoleHolders.tsx': 5,
  'features/roles/Roles.tsx': 2,
  'features/runtime/CannotStart.tsx': 3,
  'features/runtime/CanvasDock.tsx': 7,
  'features/runtime/CanvasMarks.tsx': 4,
  'features/runtime/CanvasTogether.tsx': 4,
  'features/runtime/CanvasWidgets.tsx': 7,
  'features/runtime/MessageConnections.tsx': 1,
  'features/runtime/SessionCanvas.tsx': 7,
  'features/runtime/Terminal.tsx': 3,
  'features/secrets/AddSecretRow.tsx': 2,
  'features/secrets/SecretControls.tsx': 1,
  'features/secrets/SecretsDetail.tsx': 5,
  'features/secrets/ValueChange.tsx': 4,
  'features/service-accounts/ServiceAccounts.tsx': 5,
  'features/sessions/Sessions.tsx': 3,
  'features/settings/ModelWindows.tsx': 3,
  'features/settings/Settings.tsx': 4,
  'features/setup/Setup.tsx': 3,
  'features/sign-in/SignIn.tsx': 1,
  'features/team/AgentRun.tsx': 6,
  'features/team/Start.tsx': 3,
  'features/teams/TeamActions.tsx': 7,
  'features/teams/Teams.tsx': 4,
  'shell/Dock.tsx': 3,
  'shell/Explain.tsx': 2,
  'shell/Listing.tsx': 3,
  'shell/Picker.tsx': 2,
  'shell/Rail.tsx': 1,
  'shell/Upgraded.tsx': 1,
};

/** How many stood when the count began. The sum above never passes it. */
export const STOOD_AT_THE_START = 246;
