//! An issuing authority from a seed the test generates, the certificates it
//! issues, and a fresh file-backed certificate log.

use std::error::Error;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::time::Duration;

use lys_core::Ed25519Identity;
use lys_core::ca::{CertificateAuthority, CustomExtension, IssuedCertificate};
use lys_log_store::{FileLeafStore, Log};

/// The outcome of one test.
pub type TestResult = Result<(), Box<dyn Error>>;

/// The origin of every certificate log these tests create.
const ORIGIN: &str = "example.test/lys/certificates";

/// A 32-byte seed for one identity, generated by the test.
pub fn seed() -> [u8; 32] {
    rand::random()
}

/// The identity of `seed`, loaded the way every lys identity is loaded: from
/// a key file written under `dir`.
pub fn identity(dir: &Path, name: &str, seed: [u8; 32]) -> Result<Ed25519Identity, Box<dyn Error>> {
    let path = dir.join(format!("{name}.key"));
    std::fs::write(&path, seed)?;
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
    Ok(Ed25519Identity::load(&path)?)
}

/// An issuing authority and the identity that signs its revocations, both
/// from one seed.
pub struct Issuer {
    /// The authority that issues certificates.
    pub authority: CertificateAuthority,
    /// The same identity, held to sign revocations.
    pub key: Ed25519Identity,
}

impl Issuer {
    /// The authority's 32-byte public key.
    pub fn public_key(&self) -> [u8; 32] {
        self.authority.public_key_bytes()
    }
}

/// The issuer of `seed`, its key file named `name` under `dir`.
pub fn new_issuer(dir: &Path, name: &str, seed: [u8; 32]) -> Result<Issuer, Box<dyn Error>> {
    let authority = CertificateAuthority::new(identity(dir, name, seed)?);
    let key = identity(dir, name, seed)?;
    Ok(Issuer { authority, key })
}

/// A certificate for `subject` issued by `issuer`, valid for one hour and
/// carrying `extensions`.
pub fn issue(
    issuer: &Issuer,
    subject: &str,
    extensions: Vec<CustomExtension>,
) -> Result<IssuedCertificate, Box<dyn Error>> {
    Ok(issuer
        .authority
        .issue_certificate(subject, Duration::from_secs(3600), extensions)?)
}

/// A fresh certificate log created at `path`.
pub fn open_log(path: &Path) -> Result<Log<FileLeafStore>, Box<dyn Error>> {
    FileLeafStore::create(path, ORIGIN)?;
    Ok(Log::open(FileLeafStore::open(path)?)?)
}
